services:
  - type: web
    name: sampler-frontend-angular
    runtime: static
    buildCommand: npm install && npx ng build --configuration production
    staticPublishPath: ./dist/sampler-frontend-angular/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
